<?xml version="1.0"?>
<error code="7">
    <message>A test message</message>
    <channel>
        <id>someId</id>
        <name>SomeChannel</name>
    </channel>
    <throwable class="java.lang.RuntimeException" renderedAs="java.lang.Throwable">
        <message>Test message</message>
        <stack>java.lang.RuntimeException: Test message   at
            org.jasig.portal.channels.error.ErrorDocumentTest.testGetDocument(ErrorDocumentTest.java:43)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native
            Method)   at
            sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
            at
            sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
            at java.lang.reflect.Method.invoke(Method.java:324)   at
            junit.framework.TestCase.runTest(TestCase.java:154)   at
            junit.framework.TestCase.runBare(TestCase.java:127)   at
            junit.framework.TestResult.protect(TestResult.java:106)
            at
            junit.framework.TestResult.runProtected(TestResult.java:124)
            at junit.framework.TestResult.run(TestResult.java:109)   at
            junit.framework.TestCase.run(TestCase.java:118)   at
            junit.framework.TestSuite.runTest(TestSuite.java:208)   at
            junit.framework.TestSuite.run(TestSuite.java:203)   at
            org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:421)
            at
            org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:305)
            at
            org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:186) </stack>
    </throwable>
</error>